ALTER TABLE tracked_tokens ADD COLUMN call_volume_h1 REAL;
ALTER TABLE tracked_tokens ADD COLUMN call_volume_h6 REAL;
ALTER TABLE tracked_tokens ADD COLUMN call_txns_h1 INTEGER;
ALTER TABLE tracked_tokens ADD COLUMN m8_at INTEGER;
ALTER TABLE tracked_tokens ADD COLUMN m8_price REAL;
ALTER TABLE tracked_tokens ADD COLUMN m8_mcap REAL;
ALTER TABLE tracked_tokens ADD COLUMN m8_liq REAL;
ALTER TABLE tracked_tokens ADD COLUMN m8_vol_h1 REAL;
ALTER TABLE tracked_tokens ADD COLUMN m8_mult REAL;
ALTER TABLE tracked_tokens ADD COLUMN m16_at INTEGER;
ALTER TABLE tracked_tokens ADD COLUMN m16_price REAL;
ALTER TABLE tracked_tokens ADD COLUMN m16_mcap REAL;
ALTER TABLE tracked_tokens ADD COLUMN m16_liq REAL;
ALTER TABLE tracked_tokens ADD COLUMN m16_vol_h1 REAL;
ALTER TABLE tracked_tokens ADD COLUMN m16_mult REAL;
ALTER TABLE tracked_tokens ADD COLUMN m24_at INTEGER;
ALTER TABLE tracked_tokens ADD COLUMN m24_price REAL;
ALTER TABLE tracked_tokens ADD COLUMN m24_mcap REAL;
ALTER TABLE tracked_tokens ADD COLUMN m24_liq REAL;
ALTER TABLE tracked_tokens ADD COLUMN m24_vol_h1 REAL;
ALTER TABLE tracked_tokens ADD COLUMN m24_mult REAL;
CREATE INDEX IF NOT EXISTS idx_tracked_m8  ON tracked_tokens(m8_mcap, m8_liq);
CREATE INDEX IF NOT EXISTS idx_tracked_m24 ON tracked_tokens(m24_mcap, m24_liq);
