name = "j33t-intel-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "j33t-intel-db"
database_id = "e17b6f3b-1382-4e9b-93bd-53264eeb6bd6"

[vars]
ENVIRONMENT = "production"
